EFFECTIF = 10    # Nombre de particules
NBLIEUX_T = 3
NBLIEUX_P = 2
TAILLE  = 800    # Taille de la fenêtre
R = 7            # Taille des rayons des particules 
RB = 30
MMD = 5          # Distance Maximale de deplacement par temps
MA = 45          # Angle maximal de rotation par temps (en degrés)
DELAY = 0.1     # Delai entre chaque temps (en seconde)
DC = 20         #Distance maximale de connection
